<x-mail::message>
# Report Card Available

Dear Parent / Guardian,

The report card for **{{ $studentName }}** — Term {{ $term }}, {{ $year }} — has been shared with you by **{{ $teacherName }}**@if($schoolName) from **{{ $schoolName }}**@endif.

Click the button below to view the full report card in your browser. No account or login is required.

<x-mail::button :url="$shareUrl" color="primary">
View Report Card
</x-mail::button>

Or copy this link into your browser:

`{{ $shareUrl }}`

---

*This link was generated by {{ $teacherName }} and is intended only for the parent or guardian of {{ $studentName }}. Please do not share it further.*

Thanks,<br>
{{ config('app.name') }}
</x-mail::message>
